
#Each new term in the Fibonacci sequence is generated by adding the 
#previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not 
#exceed four million, find the sum of the even-valued terms.

def getSum():
	_sum = 0 
	x = 1#start sequence at 1
	y = 0
	while(y<=4000000):#go to 4 milly
		y = y + x#add last two numbers to make new number
		if(y%2==0):#if number is even, add it
			_sum += y
	return _sum

if __name__ == "__main__":
	print(getSum())